### ISSUE TITLE
Breaks next/previous tab switching

### ISSUE THREAD

**Issue by valorin** [ArnaudRinquin/atom-zentabs#12]
Zentabs breaks next/previous tab switching when it starts removing old tabs. Since it extracts tabs and replaces them randomly, the order gets stuffed up and the order of tabs becomes a weird order, rather than logical left<->right.

To reproduce, open a bunch of tabs, randomly editing different ones in different orders, and keep opening. It will eventually start removing randomly positioned tabs, which breaks the next/previous switcher order.

**Comment by theblacklion** [comment]
Any progress here?

**Comment by ArnaudRinquin** [comment]
I just tried to reproduce, without being able to reproduce this time. I think it got fixed in the tab component.

**Comment by ArnaudRinquin** [comment]
Actually, this seems to break at some point. I really don't think it comes from my code. I am just calling `@pane.destroyItem`, which is the regular way of closing tabs. The tab view just doesn't take that into account.

**Comment by ArnaudRinquin** [comment]
Tried to reproduce again, without success. It has probably been fixed in `atom/tabs`
