### ISSUE TITLE
Zentabs assigns the very frequently used ctrl+shift+Z

### ISSUE THREAD

**Issue by DiThi** [ArnaudRinquin/atom-zentabs#13]
It's "redo" in many applications, and I find it much more useful than ctrl-y (both are assigned in atom) because I can undo and redo very quickly without moving the hand.

**Comment by theblacklion** [comment]
Currently it owns ctrl-z which is "undo". Please find something else. I would even vote for removing or disabling the keyboard shortcut by default. Having it in the command palette should be enough.

**Comment by ArnaudRinquin** [comment]
Oh I forgot about this one. Hum. I'll add a note in the `README` about the shortcut and remove it for now.
