### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by caedes** [ArnaudRinquin/atom-zentabs#15]
`atom.workspaceView` is no longer available.

In most cases you will not need the view. See the [Workspace docs for
alternatives](https://atom.io/docs/api/latest/Workspace).

If you do need the view, please use `atom.views.getView(atom.workspace)`, which returns an HTMLElement.

```
lib/zentabs-controller.coffee:12:9
lib/zentabs-controller.coffee:13:9
lib/zentabs-controller.coffee:14:9
lib/zentabs-controller.coffee:42:9
lib/zentabs.coffee:21:11
lib/zentabs.coffee:13:29
```

**Comment by ArnaudRinquin** [comment]
Fixed in #16
