### ISSUE TITLE
Option to never close modified repo files.

### ISSUE THREAD

**Issue by theblacklion** [ArnaudRinquin/atom-zentabs#17]
What do you think about an option to also exclude modified/added repo files? For me it often comes down to that I definitely don't want my dirty files to be closed until I commit them.

**Comment by ArnaudRinquin** [comment]
That would be useful. What would be the best way to detect `dirty` files / tab?

**Comment by ArnaudRinquin** [comment]
Seems quite easy: https://atom.io/docs/api/v0.178.0/GitRepository#instance-isPathNew

I would add it but I don't have the time at the moment. On the TODO list.

**Comment by theblacklion** [comment]
Thanks @ArnaudRinquin ! :)
