### ISSUE TITLE
It's possible to open an unlimited amount of tabs when splitting

### ISSUE THREAD

**Issue by LaurentTreguier** [ArnaudRinquin/atom-zentabs#18]
If I spit the editor in order to open 2 files at the same time, the newly opened pane will be able to hold any number of tabs open, without restriction (e.g. I had a 2 tabs limit and could have 3 opened). The first pane will still be restricted and will keep the max number of tabs  open however. Tested on Atom 0.179.0, zentabs 0.8.0

**Comment by ArnaudRinquin** [comment]
I was able to replicate. Thanks for the extensive description. I'll take a look.

**Comment by ArnaudRinquin** [comment]
Fixed in `0.8.1`
