### ISSUE TITLE
Cannot disable without Atom restart

### ISSUE THREAD

**Issue by kankaristo** [ArnaudRinquin/atom-zentabs#25]
Thanks for a great package, this is very useful!

I tried using [toggle-packages](https://atom.io/packages/toggle-packages) to toggle `zentabs` on and off.

However, `zentabs` doesn't actually stop closing tabs, even if it's disabled! You can toggle "Manual Mode" on and off while the package is disabled, and that seems to work. I guess something is missing from `deactivate`.

As a temporary fix, I'm setting manual mode off in `activate` and on in `deactivate`.

**Comment by ArnaudRinquin** [comment]
This package was created in the early life of atom and might not respect the expected package lifecycle properly. I'll see what I can do.

**Comment by ArnaudRinquin** [comment]
Fixed in 8795d97a159f2ca35f5aa15134fa2f6618dc8aeb released with [`0.8.5`](https://github.com/ArnaudRinquin/atom-zentabs/tree/v0.8.5)

**Comment by kankaristo** [comment]
Thanks! :+1:
