### ISSUE TITLE
Not working in Atom 1.4.0

### ISSUE THREAD

**Issue by tomitrescak** [ArnaudRinquin/atom-zentabs#32]
Hi

Since I upgraded to Atom 1.4.0. the plugin is not working. Any idea what could be the issue? Am I the only one experiencing this problems?

Thanks

**Comment by dcaixinha** [comment]
This is also happening to me on v 1.4.1! :cry:

**Comment by ArnaudRinquin** [comment]
Hi, I run 1.4.2 but I don't have any issue. Could you please tell me more about the issue and your context (other tab related plugins, OS, etc...). I'll try to figure that out.

**Comment by tomitrescak** [comment]
Problem is on Mac OS, I have no other tab related plugins installed. Do you want me to sent you the config file? If so, which one? Thanks!

**Comment by ArnaudRinquin** [comment]
Well that seems like you've got the regular setup. What is the exact issue?

Do you mind:

1. starting atom in dev mode: `atom -d ./`
1. open dev tools (toolbar > View > Developer > Toggle Debug Tools)
1. Open the console tab
1. Copy paste me any relevant logs

Thanks

**Comment by tomitrescak** [comment]
@ArnaudRinquin A simple reinstall worked for me.

**Comment by ArnaudRinquin** [comment]
Do you mean it fixed it or that it allowed you to reproduce it?

**Comment by ArnaudRinquin** [comment]
I made a few changes to how the config is loaded, I made sure it works on a brand new config and could not reproduce any issue. Let me know if it fixed anything for you.

**Comment by tomitrescak** [comment]
Ok, I've found a culprit. Turn on all the options (do not close dirty, new ....) then, even if the tab is saved and not dirty anymore it will stay open forever.
