### ISSUE TITLE
Maximum open tabs not working

### ISSUE THREAD

**Issue by david-w** [ArnaudRinquin/atom-zentabs#47]
Atom 1.21.2  Mac OS El Capitan 10.11.6
No matter what number I enter in the Maximum open tabs setting, only one tab stays open and gets replaced by the next tab that is opened.

**Comment by yubaoquan** [comment]
I fixed it but the [PR](https://github.com/ArnaudRinquin/atom-zentabs/pull/46) is still not merged. Try this package **[zentabs-fix](https://atom.io/packages/zentabs-fix)** before the author merge my PR.

**Comment by ArnaudRinquin** [comment]
Sorry guys it took my so long. 

Thanks @yubaoquan for your contribution! Shipped as `0.8.9`

**Comment by david-w** [comment]
Sorry, but I still have this problem with version 0.8.9 and Atom 1.21.2 x64.

**Comment by david-w** [comment]
So I think it must be connected to https://github.com/ArnaudRinquin/atom-zentabs/issues/43 somehow.  When I am not opening files from within a project, zentabs works as expected.  It's only when I am opening tabs from within the Atom project side panel that this is an issue.

I'm not expecting a fix for this, just putting it out here.
Thanks @ArnaudRinquin
