### ISSUE TITLE
tabs all closing

### ISSUE THREAD

**Issue by nickfmc** [ArnaudRinquin/atom-zentabs#48]
Latest Atom update 1.22.0 ia32 appears to have added a bug where when I reach my tab limit, all my tabs close down not just the first opened

**Comment by AlexWayfer** [comment]
This issue is very critical! @ArnaudRinquin, pay attention, please.

**Comment by ArnaudRinquin** [comment]
Sorry guys it took my so long.

Shipped as `0.8.9`

**Comment by AlexWayfer** [comment]
@ArnaudRinquin, thank you!
