### ISSUE TITLE
Deprecated selector in `zentabs\node_modules\atom-space-pen-views\stylesheets\select-list.less

### ISSUE THREAD

**Issue by ghost** [ArnaudRinquin/atom-zentabs#54]
In `zentabs\node_modules\atom-space-pen-views\stylesheets\select-list.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow,
atom-text-editor .gutter .line-number,
atom-text-editor .line` => `atom-text-editor.editor,
atom-text-editor .gutter .line-number,
atom-text-editor .line`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by NicoLiam** [comment]
- - [x] - @NicoLiam ![image](https://user-images.githubusercontent.com/38382081/115930279-76784380-a489-11eb-863e-7a8dec56665d.jpeg)
